# Generated by Django 4.0.1 on 2022-01-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('habilidad', models.CharField(max_length=40)),
                ('numero', models.IntegerField()),
                ('apariencia', models.ImageField(upload_to='sprites/')),
                ('tipo', models.ManyToManyField(to='pokepedia.Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Batalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion', models.TimeField()),
                ('luchadores', models.ManyToManyField(to='pokepedia.Pokemon')),
            ],
        ),
    ]
