# Generated by Django 4.0.1 on 2022-01-25 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokepedia', '0002_remove_batalla_duracion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipo',
            options={'verbose_name': 'Tipo', 'verbose_name_plural': 'Tipos'},
        ),
    ]
