# Generated by Django 4.0.1 on 2022-01-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokepedia', '0003_alter_tipo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batalla',
            options={'verbose_name': 'Batalla', 'verbose_name_plural': 'Batallas'},
        ),
        migrations.AlterModelOptions(
            name='pokemon',
            options={'verbose_name': 'Pokemon', 'verbose_name_plural': 'Pokemones'},
        ),
        migrations.AddField(
            model_name='batalla',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='tipo',
            field=models.ManyToManyField(related_name='mis_pokemones', to='pokepedia.Tipo', verbose_name='Tipos'),
        ),
    ]
