# Generated by Django 4.0.1 on 2022-01-26 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokepedia', '0004_alter_batalla_options_alter_pokemon_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batalla',
            name='ganador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ganador', to='pokepedia.pokemon'),
        ),
    ]
