# Generated by Django 4.0.1 on 2022-01-26 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokepedia', '0006_lugar_alter_pokemon_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='batalla',
            name='lugar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lugar', to='pokepedia.lugar'),
        ),
    ]
