# Generated by Django 4.0.1 on 2022-02-21 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokepedia', '0007_batalla_lugar'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='victorias',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='batalla',
            name='lugar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokepedia.lugar'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='numero',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='tipo',
            field=models.ManyToManyField(to='pokepedia.Tipo'),
        ),
    ]
