# Generated by Django 4.0.1 on 2022-02-21 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokepedia', '0010_remove_batalla_victorias_pokemon_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='fecha',
        ),
    ]
